title: Хекслет.Поддержка
description: Как работает Хекслет и связанные с этим вопросы
baseurl: ""
url: "https://hexlet.github.io"
include:
  - articles/*.md
  - categories/*.md
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
markdown: kramdown
encoding: utf-8
sass:
  quiet_deps: true
