title: Хекслет.Поддержка
description: Как работает Хекслет и связанные с этим вопросы
baseurl: ""
url: "https://hexlet.github.io"
include:
  - articles/*.md
  - categories/*.md
theme: just-the-docs
markdown: kramdown
encoding: utf-8
sass:
  quiet_deps: true
