title: Хекслет.Поддержка
description: Как работает Хекслет и связанные с этим вопросы
baseurl: ""
url: "https://hexlet.github.io"
theme: jekyll-theme-minimal
markdown: kramdown
encoding: utf-8
sass:
  quiet_deps: true
