title: Хекслет.Поддержка
description: Как работает Хекслет и связанные с этим вопросы
baseurl: ""
url: https://hexlet.github.io/
include:
  - articles
  - categories
theme: minima
kramdown:
  input: kramdown
